### ISSUE TITLE
Rabix with matplotlib

### ISSUE THREAD

**Issue by dyermd** [rabix/rabix#138]
I am running into an issue when trying to use matplotlib in a script as part of my Rabix workflow. It appears to be released to how the user ID is setup when Rabix makes the docker call.

```
Traceback (most recent call last):
  File "/usr/src/app/mapping-stats.py", line 7, in <module>
    import matplotlib
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1102, in <module>
    rcParams = rc_params()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 949, in rc_params
    fname = matplotlib_fname()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 770, in matplotlib_fname
    configdir = _get_configdir()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 635, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 612, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 544, in _create_tmp_config_dir
    tempdir = os.path.join(tempdir, 'matplotlib-%s' % getpass.getuser())
  File "/usr/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 501'
```

If I run docker myself it works fine.

**Comment by StarvingMarvin** [comment]
We are running docker with UID of host user so that produced files are readable on host. It mostly works except when tool tries to resolve pid to user as in this case. Two solutions are to 'fix' tool image by adding a user with given uid and that running it, or to run as root and then chown results. Since matplotlib is basically the only tool that ever failed for this reason, we ended up not fixing it at all. First solution is a bit hacky, and second is a potential security issue in case of malicious tool escaping from container.

Would a command line option as to specify container user be an OK fix?

**Comment by cancan101** [comment]
I posted this upstream: https://github.com/matplotlib/matplotlib/issues/5940.

A solution is to set `MPLCONFIGDIR=/tmp/` in the Dockerfile (or to any dir that is globally writeable).

**Comment by dyermd** [comment]
Thanks @cancan101
