### ISSUE TITLE
Failed to start in centOS 7

### ISSUE THREAD

**Issue by gezthxbio** [rabix/rabix#146]
[fastqc_ver2-0.cwl.txt](https://github.com/rabix/rabix/files/1551618/fastqc_ver2-0.cwl.txt)
[nohup.out.txt](https://github.com/rabix/rabix/files/1551571/nohup.out.txt)
Im new to rabix. Tried to run a cwl for fastqc admin/sbg-public-data/fastqc-0-11-4/8 
rabix fastqc_ver2-0.cwl -- --input_fastq_R1 SRR6058781_1.fastq --input_fastq_R2 SRR6058781_2.fastq
[2017-12-12 16:31:04.837] [INFO] Job root.fastqc_0_11_4 has started
[2017-12-12 16:31:04.848] [ERROR] Failed to start 5396509c-8fbf-4336-a74d-b3ad7b36a395. org.rabix.executor.ExecutorException: Execution failed for 5396509c-8fbf-4336-a74d-b3ad7b36a395. null
org.rabix.executor.ExecutorException: Execution failed for 5396509c-8fbf-4336-a74d-b3ad7b36a395. null
        at org.rabix.executor.handler.impl.JobHandlerImpl.start(JobHandlerImpl.java:186) ~[rabix-cli.jar:na]
        at org.rabix.executor.execution.command.StartCommand.run(StartCommand.java:32) ~[rabix-cli.jar:na]
        at org.rabix.executor.execution.JobHandlerCommand.run(JobHandlerCommand.java:51) [rabix-cli.jar:na]
        at org.rabix.executor.execution.JobHandlerRunnable.run(JobHandlerRunnable.java:58) [rabix-cli.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.lang.NullPointerException: null

Full log & cwl is

 attached.

**Comment by milos-ljubinkovic** [comment]
Sorry about that, we redesigned our file api recently and some bugs appeared. This will be fixed in the next release but until then you can work around it by referencing the app file with a full path instead of just the name:

`rabix ./fastqc_ver2-0.cwl -- --input_fastq_R1 SRR6058781_1.fastq --input_fastq_R2 SRR6058781_2.fastq`

or an absolute path like `rabix /home/biouser/fastqc_ver2-0.cwl ...`

**Comment by gezthxbio** [comment]
Tried `/home/biouser/bin/rabix-cli-1.0.3/rabix /home/biouser/rabix/fastqc_ver2-0.cwl -- --input_fastq_R1 /home/biouser/rabix/SRR6058781_1.fastq --input_fastq_R2 /home/biouser/rabix/SRR6058781_2.fastq`

and with `./filename`

same error.

**Comment by gezthxbio** [comment]
I tried to pull a develop branch
`git clone https://github.com/rabix/bunny.git
cd bunny
git checkout develop
mvn clean install -P all
`
executed command

`sudo ./rabix ../fastqc_ver2-0.cwl -- --input_fastq_R1 ../SRR6058781_1.fastq --input_fastq_R2 ../SRR6058781_2.fastq`

got this error
`[2017-12-13 16:52:23.980] [INFO] Job root.fastqc_0_11_4 has started
[2017-12-13 16:52:26.596] [INFO] Pulling docker image images.sbgenomics.com/mladenlsbg/fastqc:0.11.4
[2017-12-13 16:52:27.215] [INFO] Running command line: fastqc  --noextract --outdir . --threads 2 /home/biouser/AGBL_LABS/rabix/SRR6058781_1.fastq /home/biouser/AGBL_LABS/rabix/SRR6058781_2.fastq
[2017-12-13 16:52:27.687] [WARN] Start container method timed-out but still started the container, recovering.
[2017-12-13 16:52:28.749] [ERROR] Job root.fastqc_0_11_4 failed with exit code 128.
[2017-12-13 16:52:28.750] [INFO] Job root.fastqc_0_11_4 failed with exit code 128.
[2017-12-13 16:52:28.757] [WARN] Job root.fastqc_0_11_4, rootId: 360ca276-26de-4caa-9e63-d0163a380fb1 failed: Job root.fastqc_0_11_4 failed with exit code 128.
[2017-12-13 16:52:28.761] [WARN] Root job 360ca276-26de-4caa-9e63-d0163a380fb1 failed.`

is there a way to check whether the docker service is running properly

**Comment by milos-ljubinkovic** [comment]
There seems to be some issues with docker on CentOS, we've seen this `Start container method timed-out` error before. But it seems that something failed inside of the running container.

Those docker containers should remain in the system, you can list them with "docker ps -a" command and finding the container that exited with this exit code (128) and then getting its logs with "docker logs {container id}".

We already have a branch that automatically gets these logs on task fail and prints it out, so this will not be necessary on the next release.

**Comment by gezthxbio** [comment]
@milos-ljubinkovic you are correct. I killed the docker process and restarted it with 
`systemctl start docker`
`systemctl enable docker`
its working now.
Thanks for the help.
